var EntitySchema = require("typeorm").EntitySchema
module.exports = new EntitySchema({
    name:"Chat",
    tableName:"Chats",
    columns:{
        chat_id:{
            primary:true,
            generated:true,
            name:"id",
            type:"int",
        },
        last_changed:{
            type:"date",
            unique:false,
            nullable:true,
            name:"last_changed",
        },
        message_history:{
            type:"text",
            unique:false,
            nullable:true,
            name:"message_history"
        }
    },
    relations:{
        member:{
            target:"User",
            type:"many-to-one",
            joinColumns:{
                name:"user_id",
                ReferencedColumnName:"user_id"
            },
        },
        guild:{
            target:"Guild",
            type:"many-to-one",
            nullable:true,
            joinColumns:{
                name:"guild_id",
                ReferencedColumnName:"guild_id"
            },
        },
    }
})
