var EntitySchema = require("typeorm").EntitySchema
module.exports = new EntitySchema({
    name:"Guild",
    tableName:"Guilds",
    columns:{
        guild_id:{
            primary:true,
            type:"varchar",
            generated:false,
            name:"guild_id",
            unique:true
        },
        guild_name:{
            name:"guild_name",
            nullable:true,
            unique:false,
            type:"varchar"
        },
        level_system:{
            type:"boolean",
            nullable:false,
            default:false,
            name:"level_system"
        },
        log_channel:{
            type:"varchar",
            nullable:true,
            default:null,
            name:"log_channel"
        },
        guild_prefix:{
            name:"guild_prefix",
            type:"varchar",
            nullable:false,
            unique:false,
            default:"-"
        },
        guild_profanity:{
            type:"boolean",
            nullable:true,
            default:false,
            name:"guild_profanity"
        },
        profanity_channel:{
            type:"varchar",
            nullable:true,
            default:null,
            name:"profanity_channel",
            unique:false
        },
        guild_chatbot:{
            type:"boolean",
            nullable:true,
            default:false,
            name:"guild_chatbot",
        },
        welcome:{
            name:"welcome",
            type:"boolean",
            nullable:true,
            default:false
        },
        welcome_channel:{
            name:"welcome_channel",
            type:"varchar",
            nullable:true,
            default:null,
            unique:false
        },
        welcome_message:{
            name:"welcome_message",
            type:"text",
            nullable:false,
            default:"**welcome** ${name} joined us.",
            unique:false,
        },
        leave_message:{
            name:"leave_message",
            type:"text",
            nullable:false,
            default:"**oh no**\n ${name} left.",
            unique:false
        }
    },
    relations:{
        messages:{
            target:"Message",
            type:"one-to-many",
            joinTable:true,
            nullable:true,
            cascade:true
        },
        warnings:{
            target:"Warning",
            type:"one-to-many",
            joinTable:true,
            cascade:true,
            nullable:true
        },
        custom_swearlist:{
            target:"Custom_Swear",
            type:"one-to-one",
            joinTable:true,
            cascade:true,
            nullable:true
        }
    },
    createGuild(
        guildID,
        level_system=false,
        log_channel,
        prefix="-",
        profanity=false,
        profanity_channel,
        welcome=false,
        welcome_channel){
    const g = new Guild();
    g.guild_id=guildID
    g.level_system=level_system
    g.log_channel=log_channel
    g.guild_prefix=prefix
    if(profanity){
        g.guild_profanity=profanity
        g.profanity_channel=profanity_channel
    }
    if(welcome){
        g.welcome=welcome
        g.welcome_channel=welcome_channel
    }
    Guild.save(g);
}
});
