var EntitySchema = require("typeorm").EntitySchema
module.exports = new EntitySchema({
    name:"Member",
    tableName:"Members",
    columns:{
        user_id:{
            name:"user_id",
            unique:true,
            primary:true,
            generated:false,
            type:"varchar"
        },
        user_name:{
            name:"user_name",
            nullable:true,
            unique:false,
            type:"varchar",
        },
        user_level:{
            name:"user_level",
            nullable:false,
            default:0,
            type:"numeric"
        },
        is_ignored:{
            name:"is_ignored",
            nullable:true,
            type:"boolean",
            default:false,
        },
        user_experience:{
            name:"user_experience",
            nullable:false,
            default:0,
            type:"numeric",
        },
        user_score:{
            name:"user_score",
            nullable:false,
            default:1000,
            type:"numeric",

        } 
    },
    relations:{
        playlists:{
            target:"Playlist",
            type:"one-to-many",
            nullable:true,
            joinTable:true,
            cascade:true,
        },
        messages:{
            target:"Message",
            type:"one-to-many",
            joinTable:true,
            cascade:true,
            nullable:true
        },
        warnings:{
            target:"Warning",
            type:"one-to-many",
            joinTable:true,
            cascade:false,
            nullable:true,
        },
    }
});