var EntitySchema = require("typeorm").EntitySchema
module.exports = new EntitySchema({
    name:"Playlist",
    tableName:"Playlists",
    columns:{
        playlist_id:{
            primary:true,
            generated:true,
            type:"int",
            name:"playlist_id"
        },
        playlist_name:{
            type:"varchar",
            name:"playlist_name",
            nullable:false,
            unique:false,
        },
    },
    relations:{
        member:{
            target:"User",
            type:"many-to-one",
            nullable:false,
            cascade:false,
            joinColumns:{name:"user_id",
            referencedColumnName:"user_id"
        },
        songs:{
            target:"Song",
            type:"one-to-many",
            nullable:true,
            one:{
                name:"playlist_id",
                referencedColumnName:"song_id",
                cascade:["delete"],
                onDelete:"CASCADE",
                eager:true,
            }
        }
        }
    }
})