var EntitySchema = require("typeorm").EntitySchema
module.exports = new EntitySchema({
    name:"User",
    tableName:"Users",
    columns:{
        user_id:{
            name:"user_id",
            unique:true,
            primary:true,
            generated:false,
            type:"varchar"
        },
        user_name:{
            name:"user_name",
            nullable:true,
            unique:false,
            type:"varchar",
        },
        user_level:{
            name:"user_level",
            nullable:false,
            default:0,
            type:"numeric"
        },
        is_ignored:{
            name:"is_ignored",
            nullable:false,
            type:"boolean",
            default:false,
        },
        user_experience:{
            name:"user_experience",
            nullable:false,
            default:0,
            type:"numeric",
        },
        user_score:{
            name:"user_score",
            nullable:false,
            default:1000,
            type:"numeric",
        } 
    },
    relations:{
        playlists:{
            target:"Playlist",
            type:"one-to-many",
            nullable:true,
            cascade:true,
            one:{
                name:"user_id",
                referencedColumnName:"playlist_id",
                cascade:["delete"],
                onDelete:"CASCADE",
                eager:true,
            }
        },
        messages:{
            target:"Message",
            type:"one-to-many",
            cascade:true,
            nullable:true,
            one:{
                name:"message_id",
                referencedColumnName:"message_id",
                cascade:["delete"],
                onDelete:"CASCADE",
                eager:true,
            }

        },
        warnings:{
            target:"Warnings",
            type:"one-to-many",
            cascade:false,
            nullable:true,
            one:{
                name:"warning_id",
                referencedColumnName:"warning_id"
            }
        },
    }
});